jwt.secret=CH8fwAUcDztKYZUM6g2NTGG4aG00jQUCnobu9sY3ESf87ilLL1B7xVOvsQTPnfUD
# Next.js \ub85c\uadf8\uc778 \uc8fc\uc18c
next.login.url=http://localhost:3000/login
# Next.js \ud504\ub860\ud2b8\uc5d4\ub4dc \uc8fc\uc18c
next.frontend.url=http://localhost:3000
# JSP \ucee8\ud14d\uc2a4\ud2b8 \uacbd\ub85c
jsp.board.url=/